
export const initialEnhancedPrompt = `
# Your Enhanced Prompt Will Appear Here

This is where the structured, step-by-step prompt generated by the AI will be displayed.

### How it works:
1.  **Enter your idea:** Type a simple coding request in the input box on the left.
2.  **Click Enhance:** Our AI will analyze your request and expand it.
3.  **Get a detailed prompt:** You'll receive a professional-grade prompt with sections like:
    *   **Role and Goal:** Defines the AI's persona.
    *   **Context:** Provides necessary background.
    *   **Step-by-Step Guide:** A clear implementation plan.
    *   **Constraints:** Sets the rules and boundaries.
    *   **Output Format:** Specifies the desired result.

Ready to generate better code? Give it a try!
`;
